added confirmation_&_snackbar🪚
RYAZHAPOVILNUR/mentoring-base pull request #117
Opened 2024-10-16 08:25 UTC by rabiulawal1422

<img width="1680" alt="Screenshot 2024-10-16 at 17 23 17" src="https://github.com/user-attachments/assets/848124aa-e766-4533-b2a5-983e6de496ee">

2024-10-16 12:49 UTC, pocahontassss requested changes

2024-10-16 12:49 UTC, pocahontassss commented on src/app/users-list/user-card/user-card.component.html
> +      <button (click)="openDialogTwo()" mat-button>СОЗДАТЬ</button>
Неправильные названия методов. Не понятно что какой метод открывает.

2024-10-16 12:49 UTC, pocahontassss commented on src/app/todos-list.component/todo-card/todo-card.component.ts
> +  }
Что за испанский язык? confirmado, dialogo, somtrar?

2024-10-16 12:49 UTC, pocahontassss commented on src/app/todos-list.component/todo-card/todo-card.component.html
> +      <button (click)="openDialogTwo()" mat-button>СОЗДАТЬ</button>
В карточке создать новую карточку? Нонсенс. Нужно убрать такое

2024-10-16 12:49 UTC, pocahontassss commented on src/app/todos-list.component/todo-card/edit-todo-dialog/edit-todo-dialog.component.html
> +        </button>
Неподходящая иконка. add - добавить. Как она связана с редактированием?

2024-10-16 12:49 UTC, pocahontassss commented on src/app/todos-list.component/todo-card/delete-todo-confirmation/delete-todo-confirmation.component.ts
> +      this.snackBar.open('ЗАДАЧА удалёна🐒', 'Закрыть', {
удалЕна*

2024-10-16 12:49 UTC, pocahontassss commented on src/app/todos-list.component/todo-card/delete-todo-confirmation/delete-todo-confirmation.component.ts
> +    }
снова испанский)

2024-10-16 12:49 UTC, pocahontassss commented on src/app/todos-list.component/todo-card/delete-todo-confirmation/delete-todo-confirmation.component.scss
> +        background-color: red;
Цвет всегда в хэше указываем

2024-10-16 12:49 UTC, pocahontassss commented on src/app/todos-list.component/todo-card/delete-todo-confirmation/delete-todo-confirmation.component.html
> +        <p>{{mensaje}}</p>
испанский

2024-10-16 12:49 UTC, pocahontassss commented on src/app/todos-list.component/todo-card/create-todo-dialog/create-todo-dialog.component.ts
> +}
Если валидатор используется в двух и больше местах, тогда его нужно вынести в отдельный файл и просто импортировать

2024-10-16 12:49 UTC, pocahontassss commented
Путь нельзя указывать, начиная от своего локального ПК. Я видел к Todo у тебя указан он именно так.

2024-10-17 11:59 UTC, shepherd1422 commented on src/app/users-list/user-card/user-card.component.html
> +      <button (click)="openDialogTwo()" mat-button>СОЗДАТЬ</button>
сделал🎗️

2024-10-17 12:01 UTC, rabiulawal1422 commented on src/app/todos-list.component/todo-card/todo-card.component.ts
> +  }
сделал

2024-10-17 12:02 UTC, rabiulawal1422 commented on src/app/todos-list.component/todo-card/edit-todo-dialog/edit-todo-dialog.component.html
> +        </button>
сделал

2024-10-17 12:05 UTC, rabiulawal1422 commented on src/app/todos-list.component/todo-card/delete-todo-confirmation/delete-todo-confirmation.component.ts
> +      this.snackBar.open('ЗАДАЧА удалёна🐒', 'Закрыть', {
сделал

2024-10-17 12:20 UTC, rabiulawal1422 commented on src/app/todos-list.component/todo-card/delete-todo-confirmation/delete-todo-confirmation.component.ts
> +    }
### сделал

2024-10-17 12:22 UTC, rabiulawal1422 commented on src/app/todos-list.component/todo-card/delete-todo-confirmation/delete-todo-confirmation.component.scss
> +        background-color: red;
### сделал

2024-10-17 12:22 UTC, rabiulawal1422 commented on src/app/todos-list.component/todo-card/delete-todo-confirmation/delete-todo-confirmation.component.html
> +        <p>{{mensaje}}</p>
### сделал

2024-10-17 12:23 UTC, rabiulawal1422 commented on src/app/todos-list.component/todo-card/create-todo-dialog/create-todo-dialog.component.ts
> +}
### сделал

2024-10-17 12:56 UTC, rabiulawal1422 commented on src/app/todos-list.component/todo-card/todo-card.component.html
> +      <button (click)="openDialogTwo()" mat-button>СОЗДАТЬ</button>
### сделал

2024-10-18 19:55 UTC, pocahontassss approved these changes

2024-10-18 19:56 UTC, closed without merging