карточки д/з
RYAZHAPOVILNUR/mentoring-base pull request #118
Opened 2024-10-16 13:56 UTC by Radmil11

@radmilahi

2024-10-17 10:24 UTC, pocahontassss requested changes

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.html
> +        <div class="header-nav-item">Каталог</div>
Не дивы, а ссылки

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.html
> +            <img class="Cart" src="/assets/Cart.svg" alt="">
Не нужно использовать атрибуты, у которых нет значения (alt)

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.html
> +            </nav>
не nav, а div, в котором это все - кнопки

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.html
> +            <p style="color: rgb(149, 149, 149);">наличии</p>
Можно создать класс и его навешивать сюда, стараемся в шаблоне не стилизовать

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.html
> +                    <p>герметики</p>
Можно ограничить ширину контейнера для того, что бы перенести текст на следующую строку.
Подход как у тебя - неверный.

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.scss
> +    padding: 0 180px;
Указываем значения всегда с px.
0px 180px

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.scss
> +    color: white;
Цвета всегда в хэше указываем

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.scss
> +    color: white;
Цвета всегда в хэше указываем

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.scss
> +    margin: 10px 10px 10px 10px;
Можно просто указать margin: 10px

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.scss
> +    font-family: Inter;
Один раз прописать в глобальных стилях и забыть

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.scss
> +    background-image: url(/assets/image19.png);
Путь к файлу указываем в кавычках. ("ссылка")

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.scss
> +}
поплыла табуляция

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.scss
> +}
поплыла табуляция

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.scss
> +}
табуляция

2024-10-17 10:24 UTC, pocahontassss commented on src/app/app.component.scss
> +    margin-top:-17px;
пробел после : нужен

2024-10-17 10:27 UTC, pocahontassss requested changes

2024-10-17 10:27 UTC, pocahontassss commented on src/assets/Arrow_6.svg
https://docs.google.com/document/u/0/d/1ipRxAtW0KEC5bj-vWLNk-p8AwjsN0AWmN8YApyP9VJw/mobilebasic
(Здесь про наименование файлов изображений и как правильно указывать пути к ним)
У тебя плохо именованы файлы картинок

2024-10-19 11:33 UTC, Radmil11 commented on src/app/app.component.html
> +        <div class="header-nav-item">Каталог</div>
ссылка это тег <a> ? исправил

2024-10-19 11:33 UTC, Radmil11 commented on src/app/app.component.html
> +            <img class="Cart" src="/assets/Cart.svg" alt="">
в данном случае нужно просто убрать alt="" отсюда ? исправил

2024-10-19 11:33 UTC, Radmil11 commented on src/app/app.component.html
> +            </nav>
исправил

2024-10-19 11:35 UTC, Radmil11 commented on src/app/app.component.scss
> +    padding: 0 180px;
готово

2024-10-19 11:37 UTC, Radmil11 commented on src/app/app.component.scss
> +    color: white;
обьясни пожаулйста что такое хэш, не понимаю

2024-10-19 11:39 UTC, Radmil11 commented on src/app/app.component.scss
> +    margin: 10px 10px 10px 10px;
готово

2024-10-19 11:41 UTC, Radmil11 commented on src/app/app.component.scss
> +    font-family: Inter;
обьясни пожалуйста где именно прописать ?

2024-10-19 11:47 UTC, Radmil11 commented on src/app/app.component.scss
> +    background-image: url(/assets/image19.png);
исправил

2024-10-19 11:50 UTC, Radmil11 commented on src/app/app.component.scss
> +    margin-top:-17px;
исправил

2024-10-19 11:51 UTC, Radmil11 commented on src/app/app.component.scss
> +}
обьясни пожалуйста что такое поплыла табуляция ?

2024-10-20 12:43 UTC, Radmil11 commented on src/app/app.component.html
> +                    <p>герметики</p>
убрал теги <p>, добавил в css max-width: 15vw. Такой подход верен ? если нет пожалуйста обьясни как правильно ?

2024-10-20 12:56 UTC, Radmil11 commented on src/app/app.component.scss
> +}
обьясни пожалуйста что такое поплыла табуляция ?

2024-10-20 13:25 UTC, Radmil11 commented on src/assets/Arrow_6.svg
прочитал понял, исправить нынешние обязательно? или могу оставить, а следующие фаилы уже писать правильно ?

2024-10-20 14:29 UTC, pocahontassss commented on src/app/app.component.html
> +                    <p>герметики</p>
Да, только не vw, а другой метод измерения. Пиксели задай лучше

2024-10-20 14:29 UTC, pocahontassss commented on src/app/app.component.scss
> +    color: white;
Да

2024-10-20 14:30 UTC, pocahontassss commented on src/app/app.component.scss
> +    font-family: Inter;
В style.scss. (там находятся глобальные стили). Мы пишем, что для body { font-family: Inter } и тогда он у нас будет работать на глобальном уровне в приложении и не придется каждому классу отдельно писать данное свойство

2024-10-20 14:31 UTC, pocahontassss commented on src/app/app.component.scss
> +}
Табуляция - отступ, выравнивание текста. Загугли про это, почитай кратко

2024-10-20 14:31 UTC, pocahontassss commented on src/app/app.component.scss
> +}
Ответ выше

2024-10-20 14:31 UTC, pocahontassss commented on src/assets/Arrow_6.svg
По возможности конечно, лучше исправить)

2024-10-20 17:08 UTC, Radmil11 commented on src/app/app.component.html
> +                    <p>герметики</p>
Задал px👍🏻

2024-10-20 17:15 UTC, Radmil11 commented on src/app/app.component.scss
> +    font-family: Inter;
сделал

2024-10-20 17:33 UTC, Radmil11 commented on src/app/app.component.html
> +            <p style="color: rgb(149, 149, 149);">наличии</p>
исправил как смог, проверь пожалуйста

2024-10-20 17:46 UTC, Radmil11 commented on src/assets/Arrow_6.svg
сделал

2024-10-20 18:11 UTC, Radmil11 commented on src/app/app.component.scss
> +}
что то не совсем понимаю, я убрал все значения во всех четырех стилях "item-cards__grid-right-block-action-link" и ничего не поменялось. в чем тут проблема обьясни пожалуйста ?

2024-10-20 18:13 UTC, Radmil11 commented on src/app/app.component.scss
> +}
все также не понимаю где именно проблема, понял что табуляция это отступ, но вот понять не могу что да как

2024-10-21 08:50 UTC, pocahontassss requested changes

2024-10-21 08:50 UTC, pocahontassss commented on src/app/app.component.scss
> +
??? Это что? Почему у них одинаковый цвет

2024-10-21 08:53 UTC, pocahontassss commented
1. Коммиты должны иметь разные названия и отображать суть твоей работы. Ты не просто добавил строку в html файл (add string in html file), как ты пишешь, а fix errors (фикс ошибок) и тд.

2. Табуляция, это когда вложенные сущности находятся на уровень глубже, чем свой родитель.
Пример табуляции:
```
<div>
    <div>
        <img>
        <span></span>
    </div>
</div>
```

Отсутствие табуляции на этом же примере:

```
<div>
<div>
<img>
<span></span>
</div>
</div>
```

Суть в том, что весь код становится в один ряд и разобраться в нем уже в разы тяжелее.

2024-10-23 14:58 UTC, Radmil11 commented on src/app/app.component.scss
> +
я тут сделал как понял короче, если неправильно обьясни мне как сделать пожалуйста

![Снимок экрана 2024-10-23 в 18 57 23](https://github.com/user-attachments/assets/0499f3f6-de18-4701-bccb-c5fbdf19bf6d)

2024-10-23 15:00 UTC, Radmil11 commented on src/app/app.component.scss
> +
вообщем я пытался делать разными цветами шрифт вот в этом месте

![Снимок экрана 2024-10-23 в 19 00 16](https://github.com/user-attachments/assets/02974ad7-d2f1-467e-a2f6-a656ed193d2a)

2024-10-23 16:24 UTC, Radmil11 commented
Могу переходить к JS ?

2024-10-23 17:00 UTC, pocahontassss approved these changes

2024-10-23 17:00 UTC, closed without merging