Yana-homework on modal dialogs
RYAZHAPOVILNUR/mentoring-base pull request #126
Opened 2024-10-18 18:42 UTC by OqTooTpO

@o8iIUIi8o

2024-10-18 19:41 UTC, pocahontassss requested changes

2024-10-18 19:41 UTC, pocahontassss commented on src/app/todos-list/todo-card/todo-card.component.ts
> +    });
Если есть openDeleteTodoDialog, значит желательно и этот назвать openEditTodoDialog)

2024-10-18 19:41 UTC, pocahontassss commented on src/app/dialogs/user-dialogs/edit-user-dialog/edit-user-dialog.component.ts
> +  constructor(public dialogRef: MatDialogRef<EditUserDialogComponent>) {}
Зачем через конструктор объявлять? Можно использовать inject как на 35 строке

2024-10-18 19:41 UTC, pocahontassss commented on src/app/dialogs/user-dialogs/edit-user-dialog/edit-user-dialog.component.ts
> +}
Можно просто использовать директиву mat-dialog-close)

2024-10-18 19:41 UTC, pocahontassss commented on src/app/dialogs/user-dialogs/delete-user-dialog/delete-user-dialog.component.ts
>    }
Просто mat-dialog-close

2024-10-18 19:41 UTC, pocahontassss commented on src/app/dialogs/user-dialogs/delete-user-dialog/delete-user-dialog.component.ts
>    constructor(public dialogRef: MatDialogRef<DeleteUserDialogComponent>) {}
Без конструктора, это устаревший метод

2024-10-18 19:41 UTC, pocahontassss commented on src/app/dialogs/todo-dialogs/edit-todo-dialog/edit-todo-dialog.component.ts
> +  }
Если форма невалидна - ты не сможешь ее отправить. Этот иф нужно убрать

2024-10-18 19:41 UTC, pocahontassss commented on src/app/dialogs/todo-dialogs/edit-todo-dialog/edit-todo-dialog.component.ts
> +      completed: this.formTodo.value.completed === 'да',
Не понял данной строки. Мы отправляем всегда форму со значением "да"?

2024-10-18 19:41 UTC, pocahontassss commented on src/app/dialogs/todo-dialogs/create-todo-dialog/create-todo-dialog.component.html
> +         formTodo.controls['title'].touched)
все эти ngIf - лишние. Они и так под капотом angular  material есть. Удали их и посмотри, что они работают

2024-10-18 19:41 UTC, pocahontassss commented on src/app/dialogs/todo-dialogs/create-todo-dialog/create-todo-dialog.component.ts
> +  };
Если ты используешь валидатор больше, чем в одном месте - его следует вынести в отдельный файл

2024-10-18 19:41 UTC, pocahontassss commented on src/app/dialogs/todo-dialogs/create-todo-dialog/create-todo-dialog.component.ts
> +  constructor(public dialog: MatDialog) {}
Снова устарелый метод

2024-10-18 19:41 UTC, pocahontassss commented on src/app/dialogs/todo-dialogs/create-todo-dialog/create-todo-dialog.component.ts
> +    });
У тебя внутри компонента create-todo-dialog есть метод по открытию этого же диалога? Чоооо

2024-10-18 19:41 UTC, pocahontassss commented on src/app/dialogs/todo-dialogs/create-todo-dialog/create-todo-dialog.component.ts
> +  }
Тоже можно вынести в отдельный файл, вместе с валидатором. Много где дублируется код

2024-10-19 14:24 UTC, OqTooTpO commented on src/app/dialogs/todo-dialogs/edit-todo-dialog/edit-todo-dialog.component.ts
> +      completed: this.formTodo.value.completed === 'да',
если значение поля completed в форме равно строке 'да', то значение ключа completed в возвращаемом объекте будет true. если нет, то  false

2024-10-23 14:54 UTC, closed without merging