new chang base
RYAZHAPOVILNUR/mentoring-base pull request #129
Opened 2024-10-19 19:20 UTC by yakupovfagim

2024-10-19 19:20 UTC, yakupovfagim commented
base

2024-10-24 21:51 UTC, pocahontassss requested changes

2024-10-24 21:51 UTC, pocahontassss commented on src/styles.scss
> +}
Шрифт называется Inter, он у тебя вряд-ли таким образом подключился. Нужно писать названия до конца

2024-10-24 21:51 UTC, pocahontassss commented on src/app/app.component.html
> +      <div class="header-nav-item">Каталог</div>
это должны быть ссылки (тег <a>)

2024-10-24 21:51 UTC, pocahontassss commented on src/app/app.component.html
> +      <span>+7 (965) 084-29-29</span>
тоже ссылка

2024-10-24 21:51 UTC, pocahontassss commented on src/app/app.component.html
> +    <div class="interier">Интерьер и одежда</div>
каталог, как и дивы (с 35 по 38 строки) должны быть кнопками. И каталог должен входить в общий див

2024-10-24 21:52 UTC, pocahontassss requested changes

2024-10-24 21:52 UTC, pocahontassss commented on src/assets/heart 1.png
Нужно поработать над названиями файлов изображений.

https://docs.google.com/document/u/0/d/1ipRxAtW0KEC5bj-vWLNk-p8AwjsN0AWmN8YApyP9VJw/mobilebasic
(Здесь про наименование файлов изображений и как правильно указывать пути к ним)

2024-11-08 06:34 UTC, yakupovfagim reviewed
yakupov fehim

2024-11-08 08:12 UTC, closed without merging