add routing in project
RYAZHAPOVILNUR/mentoring-base pull request #144
Opened 2024-10-23 09:47 UTC by Danielhan8

2024-10-23 10:13 UTC, pocahontassss requested changes
1. Поработать над названиями файлов изображений
https://docs.google.com/document/u/0/d/1ipRxAtW0KEC5bj-vWLNk-p8AwjsN0AWmN8YApyP9VJw/mobilebasic
(Здесь про наименование файлов изображений и как правильно указывать пути к ним)

2. Почистить код от ненужных комментариев, убрать дублирующийся код
3. Исправить ошибки, которые описаны в комментариях

2024-10-23 10:13 UTC, pocahontassss commented on src/assets/+7 (965) 084-29-29.svg
Это у нас не картинка, а обычный текст)

2024-10-23 10:13 UTC, pocahontassss commented on src/assets/52.png
Это тоже обычный текст

2024-10-23 10:13 UTC, pocahontassss commented on src/assets/Frame 3.png
Это должно быть сверстано

2024-10-23 10:13 UTC, pocahontassss commented on src/assets/Frame 21.png
Это тоже должно быть сверстано

2024-10-23 10:13 UTC, pocahontassss commented on src/assets/Frame 118.svg
Тоже должно верстаться

2024-10-23 10:13 UTC, pocahontassss commented on src/assets/Frame_27.png
Тоже верстается

2024-10-23 10:13 UTC, pocahontassss commented on src/assets/Frame_39.png
И это

2024-10-23 10:13 UTC, pocahontassss commented on src/assets/Frame_35.svg
И это

2024-10-23 10:13 UTC, pocahontassss commented on src/app/users-list/users-list.component.scss
> +        font-family: inter;
Можно вынести в глобальные стили (style.scss) и не прописывать каждый раз

2024-10-23 10:13 UTC, pocahontassss commented on src/app/components/header/header.component.html
> +          <div>+7(965)084-29-29</div>
Это должна быть ссылка с атрибутом href="+tel"

2024-10-23 10:13 UTC, pocahontassss commented on src/app/app.component.html
> +		<button class="plus">+</button>
весь закоментированный код нужно удалить, сдаем работу чистой

2024-10-23 10:13 UTC, pocahontassss commented on src/app/app.component.scss
> +    background-image: url(/assets/image_19.png);
ссылку на картинку указываем в кавычках. url("ссылка")

2024-10-23 10:13 UTC, pocahontassss commented on src/app/app.component.ts
> +
это можно удалить, ведь ты это делаешь уже в компоненте header

2024-10-23 11:57 UTC, Danielhan8 commented on src/assets/+7 (965) 084-29-29.svg
а как мне найти это место в коде?

2024-10-23 12:03 UTC, Danielhan8 commented on src/app/users-list/users-list.component.scss
> +        font-family: inter;
а как это сделать?

2024-10-23 12:38 UTC, Danielhan8 commented on src/app/app.component.scss
> +    background-image: url(/assets/image_19.png);
так что ли нужно? background-image: url("/assets/image_19.png");

2024-10-23 12:41 UTC, pocahontassss commented on src/app/app.component.scss
> +    background-image: url(/assets/image_19.png);
Да

2024-10-23 12:42 UTC, pocahontassss commented on src/app/users-list/users-list.component.scss
> +        font-family: inter;
body {
    font-family: Inter;
}

2024-10-23 12:42 UTC, pocahontassss commented on src/assets/+7 (965) 084-29-29.svg
В чат ответил

2024-10-23 14:24 UTC, Danielhan8 commented on src/app/users-list/users-list.component.scss
> +        font-family: inter;
font-family: Inter у меня есть в глобальных стилях, а что еще нужно добавить?

2024-10-26 17:16 UTC, pocahontassss approved these changes

2024-10-26 17:16 UTC, closed without merging