пайпы, директивы
RYAZHAPOVILNUR/mentoring-base pull request #149
Opened 2024-10-26 16:05 UTC by AzatGareev

![пайпы  4 задание](https://github.com/user-attachments/assets/37e18982-5cc0-4cc4-886b-a034261c0b37)
![пайпы  2 задание](https://github.com/user-attachments/assets/c1700cb8-61b1-4361-a690-2ae77a6b7c23)
![пайпы  1 задание](https://github.com/user-attachments/assets/6efcf40a-b0b8-4aad-9a65-6188da590ecf)

https://github.com/user-attachments/assets/a813f7bc-e558-47b7-8d4a-23ff92b8b4b8

2024-10-26 17:32 UTC, pocahontassss requested changes

2024-10-26 17:32 UTC, pocahontassss commented on src/app/users-list/user-card/user-card.component.ts
> +                this.snackBar.open('Пользователь удален', 'ok', {duration: 3000,});
Лишняя запятая после 3000

2024-10-26 17:32 UTC, pocahontassss commented on src/app/users-list/user-card/user-card.component.ts
> +    }
Если есть конкретное название для удалениеЮзера, значит должно быть и для редактирования)

2024-10-26 17:32 UTC, pocahontassss commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +    }
Лучше сделать через метод. Нужно посмотреть лекцию, которую я скидывал в чат

2024-10-26 21:00 UTC, AzatGareev commented on src/app/users-list/user-card/user-card.component.ts
> +                this.snackBar.open('Пользователь удален', 'ok', {duration: 3000,});
+

2024-10-26 21:02 UTC, AzatGareev commented on src/app/users-list/user-card/user-card.component.ts
> +    }
+

2024-10-26 21:59 UTC, AzatGareev commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +    }
+

2024-10-27 13:06 UTC, pocahontassss approved these changes

2024-10-27 13:06 UTC, closed without merging