ФОРМЫ
RYAZHAPOVILNUR/mentoring-base pull request #159
Opened 2024-10-28 15:10 UTC by Holin1945

2024-10-28 17:12 UTC, pocahontassss requested changes

2024-10-28 17:12 UTC, pocahontassss commented on src/app/create-user-form/create-user-form.ts
> +        companyName: new FormControl('', [Validators.required, Validators.minLength(2)]),
Нужно переделать форм контрол)

2024-10-28 17:12 UTC, pocahontassss commented on src/app/create-user-form/create-user-form.ts
> +    }
А это зачем?

2024-10-28 17:12 UTC, pocahontassss commented on src/app/create-todo-form/create-todo-form.ts
> +        completed: new FormControl('', [Validators.required, Validators.minLength(2)]),
А где валидатор?

2024-10-28 17:16 UTC, Holin1945 commented on src/app/create-user-form/create-user-form.ts
> +        companyName: new FormControl('', [Validators.required, Validators.minLength(2)]),
что именно ? то что в ковычках дописать ?

2024-10-28 17:16 UTC, Holin1945 commented on src/app/create-user-form/create-user-form.ts
> +    }
а это с видео, чтоб каждое действие выводилось в консоль ))

2024-10-28 17:16 UTC, Holin1945 commented on src/app/create-todo-form/create-todo-form.ts
> +        completed: new FormControl('', [Validators.required, Validators.minLength(2)]),
в ковычках ?

2024-10-30 00:10 UTC, pocahontassss approved these changes

2024-10-30 00:10 UTC, closed without merging