Домашка по уроку - СЕРВИСЫ, СОСТОЯНИЕ НА RXJS
RYAZHAPOVILNUR/mentoring-base pull request #163
Opened 2024-10-29 08:51 UTC by madiyar-yp

2024-10-29 08:58 UTC, pocahontassss requested changes

2024-10-29 08:58 UTC, pocahontassss commented on src/app/users.service.ts
> +    usersSubject = new BehaviorSubject<User[]>([])
1. нужно добавить свойство private. 
2. Ты создал поток данных userSubject. После ты должен был сделать его неизменяемым, то-есть применить оператор .asObservable, и потом с этим потоком работать, а так ты обращаешься к сабджекту.

2024-10-29 08:58 UTC, pocahontassss commented on src/app/users-list/users-list.component.html
> +        <div *ngFor="let user of usersService.usersSubject | async">
Здесь соответственно обращение будет к потоку обсервабл

2024-10-29 08:58 UTC, pocahontassss commented on src/app/todos.service.ts
> +    todosSubject = new BehaviorSubject<Todo[]>([])
Аналогично с юзерами

2024-10-29 08:58 UTC, pocahontassss commented on src/app/todos-list/todos-list.component.html
> +        <div *ngFor="let todo of todosService.todosSubject | async">
Аналогично

2024-10-29 08:58 UTC, pocahontassss commented on src/app/todos.service.ts
> +    todos: Todo[] = []
Эта строка тебе уже не нужна

2024-10-29 08:58 UTC, pocahontassss commented on src/app/users.service.ts
>      users: User[] = [];
Эта строка не нужна

2024-10-29 09:12 UTC, madiyar-yp commented on src/app/users.service.ts
> +    usersSubject = new BehaviorSubject<User[]>([])
`private readonly usersSubject = new BehaviorSubject<User[]>([])`

2024-10-29 09:14 UTC, madiyar-yp commented on src/app/users.service.ts
> +    usersSubject = new BehaviorSubject<User[]>([])
private readonly usersSubject = new BehaviorSubject<User[]>([])
приватным и неизменяемым так да? А .asObservable где писать, в уроке об этом не говорили

2024-10-30 18:01 UTC, pocahontassss approved these changes

2024-10-30 18:01 UTC, closed without merging