Task9.services, classes
RYAZHAPOVILNUR/mentoring-base pull request #180
Opened 2024-11-01 21:12 UTC by Danielhan8

Gladiolus5

2024-11-04 09:47 UTC, pocahontassss requested changes

2024-11-04 09:47 UTC, pocahontassss commented on src/app/components/header/header.component.scss
> +    max-width: none;
Можно просто убрать свойство)

2024-11-04 09:47 UTC, pocahontassss commented on src/app/users-list/user-card/user-card.component.ts
> +  user: any;
Нужна типизация

2024-11-04 09:48 UTC, pocahontassss commented on src/app/todos-list/todos-list.component.ts
> +    });
Нужна типизация

2024-11-04 09:48 UTC, pocahontassss commented on src/app/todos-list/todo-card/todo-card.component.ts
> +  todo: any;
Нужна типизация

2024-11-04 09:50 UTC, pocahontassss commented on src/app/users-list/users-list.component.html
> +<div style = " display: flex; justify-content: center;">
Вынести в класс, в html вообще не стилизуем

2024-11-06 12:24 UTC, Danielhan8 commented on src/app/components/header/header.component.scss
> +    max-width: none;
.content-container и в фугурных скобках это все удалить?

2024-11-30 15:49 UTC, closed without merging