guard, local storage
RYAZHAPOVILNUR/mentoring-base pull request #186
Opened 2024-11-04 20:31 UTC by OqTooTpO

_tg:  @ihatecowmilk_
ещё сделала кнопочку скролла вверх

https://github.com/user-attachments/assets/5e22dad2-ca61-48f3-b7c3-a765f7281ef6

2024-11-04 21:00 UTC, pocahontassss requested changes

2024-11-04 21:00 UTC, pocahontassss commented on src/app/admin.guard.ts
> +        return false;
Можно в if засунуть просто проверку на user.IsAdmin. Если user = null, значит параметра isAdmin у него нет

2024-11-04 21:00 UTC, pocahontassss commented on src/app/header/header.component.ts
> +
А это что за геттер? Не вижу, где он используется)

2024-11-04 21:00 UTC, pocahontassss commented on src/app/services/users-services/user.service.ts
А вот здесь нужно поработать.

2024-11-05 09:29 UTC, pocahontassss requested changes

2024-11-05 09:29 UTC, pocahontassss commented on src/app/users-list/users-list.component.ts
> +        this.localStorageService.saveUsersToLocalStorage('users', response); // Adjusted to use the method name
Ты не должна взаимодействовать с локальным хранилищем на уровне компонента. Этот код должен находиться в сервисе. Желательно вот прям весь метод вынести в сервис, а здесь его просто вызывать

2024-11-05 09:29 UTC, pocahontassss commented on src/app/users-list/users-list.component.ts
> +    this.localStorageService.saveUsersToLocalStorage('users', users);
Аналогично

2024-11-05 09:29 UTC, pocahontassss commented on src/app/users-list/users-list.component.ts
>      };
Пользователям такой параметр не нужен (которые карточки)

2024-11-05 09:29 UTC, pocahontassss commented on src/app/services/users-services/user.service.ts
>    }
Зачем это делать в виде метода, когда можно сделать полем. Аналогично с users.service, где мы делали поток observable, здесь-то зачем это делать через метод? И они должны в коде находиться рядом.
p.s. сущности rxjs мы указываем через $

2024-11-05 09:29 UTC, pocahontassss commented on src/app/services/users-services/user.service.ts
>    }
Для чего здесь данный метод?

2024-11-05 09:29 UTC, pocahontassss commented on src/app/services/users-services/user.service.ts
>    }
Это лучше сделать геттером

2024-11-05 09:29 UTC, pocahontassss commented on src/app/services/users-services/user.service.ts
>    }
Этот метод нам зачем?

2024-11-05 09:29 UTC, pocahontassss commented on src/app/interfaces/user-interfaces.ts
>  }
Лучше назвать userRole

2024-11-06 10:32 UTC, pocahontassss requested changes

2024-11-06 10:32 UTC, pocahontassss commented on src/app/header/header.component.ts
>  }
Нужно обработать дополнительный сценарий, когда пользователь просто жмет мимо модалки, она у него закрывается и res = undefined, а по твоему блоку он будет админом

2024-11-06 10:36 UTC, pocahontassss requested changes

2024-11-06 10:36 UTC, pocahontassss commented on src/app/services/users-services/users.service.ts
> +
Подгружать пользователей мы должны в компоненте, а не в сервисе)

2024-11-06 10:36 UTC, pocahontassss commented on src/app/services/users-services/users.service.ts
> +  }
Зачем здесь дублировать метод с local storage service?

2024-11-06 10:36 UTC, pocahontassss commented on src/app/services/users-services/users.service.ts
> +  }
Нам нужно создать метод для загрузки юзеров и его прокинуть в ngOnInit в компоненте

2024-11-06 21:30 UTC, pocahontassss approved these changes

2024-11-06 21:30 UTC, pocahontassss commented on src/app/services/users-services/users.service.ts
>    }
Странный метод. его задача просто перезаписывать поток теми же данными, которые уже находятся в localStorage? Если у нас есть данные по ключу (storedUsers true), тогда мы их суем снова в локальное хранилище и обновляем поток данных?

2024-11-06 21:30 UTC, closed without merging

2024-11-07 18:15 UTC, OqTooTpO commented on src/app/services/users-services/users.service.ts
>    }
исправила
 loadUsers(): void {
   const storedUsers = this.localStorageService.getUsersFromLocalStorage(this.localStorageKey);
   storedUsers? this.usersSubject$.next(storedUsers) : this.usersApiService.getUsers().subscribe(data => this.setUsers(data));
  }