Guard task mostly complete
RYAZHAPOVILNUR/mentoring-base pull request #187
Opened 2024-11-05 07:39 UTC by shepherd1422

![Screenshot 2024-11-05 163901](https://github.com/user-attachments/assets/cdc040da-30b5-44f6-8d46-0d4d21bade90)

2024-11-05 09:36 UTC, pocahontassss requested changes

2024-11-05 09:36 UTC, pocahontassss commented on src/app/services/local-storage.service.ts
> +  }
сервис не должен иметь конкретной реализации, он должен быть абстрактным и переиспользоваться в todos, users. То-есть методы абсолютно одинаковые, но тебе приходится их дублировать чисто из-за задач, тебе нужно сделать их переиспользуемыми.

2024-11-05 09:36 UTC, pocahontassss commented on src/app/services/auth-user.service.ts
> +}
Ну здесь нужно переписать практически всё. Ты смотрел лекцию, которую я скидывал? Мы здесь должны хранить юзера и производить его модификацию. И все состояния должны храниться в RXJS. Посмотри лекцию.

2024-11-07 06:25 UTC, shepherd1422 commented on src/app/services/auth-user.service.ts
> +}
хорощо

2024-11-11 11:07 UTC, closed without merging