guard_&_localStorage🧰🔐
RYAZHAPOVILNUR/mentoring-base pull request #195
Opened 2024-11-10 07:09 UTC by shepherd1422

![guard localStorage ](https://github.com/user-attachments/assets/7ab89c28-41f7-4405-87c3-8319441d3623)

2024-11-11 15:35 UTC, pocahontassss requested changes

2024-11-11 15:35 UTC, pocahontassss commented on src/app/services/users.service.ts
> +  }
У тебя есть метод, который включает в себя обновление потока данных и сохранение значений в локальное хранилище. Значит вместо дублирования кода с 41 по 45 строки мы засунем сюда этот метод)

2024-11-11 15:35 UTC, pocahontassss commented on src/app/services/users.service.ts
> +// }
Вот это мы за собой подчищаем

2024-11-11 15:35 UTC, pocahontassss commented on src/app/services/users.service.ts
> +}
Этот метод лишний в принципе, так как ты в каждом методе сохраняешь пользователей все равно через saveToLocalStorage

2024-11-11 15:35 UTC, pocahontassss commented on src/app/services/todos.service.ts
Сделать аналогично с юзерами

2024-11-11 15:35 UTC, pocahontassss commented on src/app/services/admin-guard.service.ts
Гвард у нас не является сервисом, убери с названия файла service, ну и он не должен храниться в этой папке

2024-11-11 15:35 UTC, pocahontassss commented on src/app/services/auth-user.service.ts
> +  }
Давай пока реализуем это без локального хранилища и не забудь геттеру модификатор доступа

2024-11-14 16:32 UTC, shepherd1422 commented on src/app/services/users.service.ts
> +  }
✔✔✔✔✔✔

2024-11-14 16:33 UTC, shepherd1422 commented on src/app/services/users.service.ts
> +}
✔✔✔✔✔✔

2024-11-14 16:33 UTC, shepherd1422 commented on src/app/services/todos.service.ts
✔✔✔✔✔✔

2024-11-14 16:34 UTC, shepherd1422 commented on src/app/services/users.service.ts
> +// }
✔✔✔✔✔✔

2024-11-14 16:44 UTC, shepherd1422 commented on src/app/services/admin-guard.service.ts
✔✔✔✔
![guard 1](https://github.com/user-attachments/assets/53821cf7-1cb2-40b7-89a9-bd0441db72f5)

2024-11-14 17:37 UTC, shepherd1422 commented on src/app/services/auth-user.service.ts
> +  }
✔✔✔✔✔

2024-11-23 12:01 UTC, pocahontassss approved these changes

2024-11-23 12:01 UTC, closed without merging