first task
RYAZHAPOVILNUR/mentoring-base pull request #221
Opened 2024-11-16 22:27 UTC by Elnurio95

2024-11-18 12:52 UTC, pocahontassss requested changes

2024-11-18 12:52 UTC, pocahontassss commented on src/assets/Frame.svg
Нужно поработать над названиями файлов изображений.

https://docs.google.com/document/u/0/d/1ipRxAtW0KEC5bj-vWLNk-p8AwjsN0AWmN8YApyP9VJw/mobilebasic
(Здесь про наименование файлов изображений и как правильно указывать пути к ним)

2024-11-18 12:52 UTC, pocahontassss commented on src/app/app.component.scss
> +    padding: 0;
Синтакический сахар соблюдаем. К нулю нужно дописать "px"

2024-11-18 12:52 UTC, pocahontassss commented on src/app/app.component.scss
> +}
Это нужно вынести в глобальные стили (style.scss)

2024-11-18 12:52 UTC, pocahontassss commented on src/app/app.component.html
> +                </ul>
Внутри li нужно поместить тег <a>

2024-11-18 18:25 UTC, Elnurio95 commented on src/assets/Frame.svg
Переименовал названия и по другому пути указал.

2024-11-18 18:31 UTC, Elnurio95 commented
Скажите, пожалуйста, почему у меня верстка такого масштаба ? Слишком приближенное :? 
И в

2024-11-21 08:25 UTC, Elnurio95 commented on src/assets/Frame.svg
fix - Changed names and directions

2024-11-21 08:26 UTC, Elnurio95 commented on src/app/app.component.scss
> +    padding: 0;
style - Add "px"

2024-11-21 08:27 UTC, Elnurio95 commented on src/app/app.component.scss
> +}
style - Make it global style

2024-11-21 08:28 UTC, Elnurio95 commented on src/app/app.component.html
> +                </ul>
> Внутри li нужно поместить тег

feat - Add links in tag li

2024-11-21 08:28 UTC, Elnurio95 commented on src/app/app.component.scss
> +}
> Это нужно вынести в глобальные стили (style.scss)

style - Make it global style

2024-11-23 12:07 UTC, pocahontassss approved these changes

2024-11-23 12:07 UTC, closed without merging