Twice task
RYAZHAPOVILNUR/mentoring-base pull request #230
Opened 2024-11-20 14:03 UTC by Rekurt-116

2024-11-20 20:35 UTC, pocahontassss requested changes

2024-11-20 20:35 UTC, pocahontassss commented on src/app/futer/futer.component.html
Пишется правильно footer*

2024-11-20 20:35 UTC, pocahontassss commented on src/app/app.component.html
> +<app-futer></app-futer>
Если app-footer, тогда уже и app-header

2024-11-20 20:35 UTC, pocahontassss commented on src/app/todos-list/todos-card/todos-card.component.html
> +</div>
Код пишем в едином стиле. то у тебя div на 3 строки, то на 1

2024-11-20 20:35 UTC, pocahontassss commented on src/app/todos-list/todos-card/todos-card.component.scss
> +}
Нет табуляции

2024-11-20 20:35 UTC, pocahontassss commented on src/app/todos-list/todos-list.component.html
> +    </div>
[todo]='todo'*

2024-11-20 20:35 UTC, pocahontassss commented on src/app/todos-list/todos-list.component.ts
> +        this.todos = response;
Нужна типизация

2024-11-20 20:35 UTC, pocahontassss commented on src/app/todos-list/todos-list.component.ts
> +      todo => {
Нужна типизация

2024-11-20 20:35 UTC, pocahontassss commented on src/app/todos-list/todos-card/todos-card.component.ts
> +  todo: any
Нужна типизация

2024-11-20 20:35 UTC, pocahontassss commented on src/app/users-list/user-card/user-card.component.ts
> +
Нужна типизация

2024-11-20 20:35 UTC, pocahontassss commented on src/app/users-list/users-list.component.html
> +    </div>
let user of users
[user]="user"

2024-11-20 20:35 UTC, pocahontassss commented on src/app/users-list/users-list.component.ts
> +
Нужна типизация
Почему у Todo есть интерфейс, у юзеров нет?

2024-11-20 20:35 UTC, pocahontassss commented on src/app/users-list/users-list.component.ts
> +                // console.log('USERS:', this.users)
Нужна типизация

2024-11-21 11:29 UTC, Rekurt-116 commented on src/app/todos-list/todos-list.component.html
> +    </div>
Спасибо за подсказку, а то я что только не делал, у меня запрос на бэк проходил а отображения не было, сейчас глянул заработало, из-за того что исправил todos на todo. Вот из-за одной буквы бывает такое, буду стараться быть внимательнее )

2024-12-07 11:10 UTC, closed without merging