Todo servise
RYAZHAPOVILNUR/mentoring-base pull request #242
Opened 2024-11-24 13:19 UTC by Rekurt-116

2024-11-24 15:38 UTC, pocahontassss requested changes

2024-11-24 15:38 UTC, pocahontassss commented on src/app/users.service.ts
> +usersSubjects: Observable<undefined> | Subscribable<undefined> | Promise<undefined> | undefined;
Эти строки нужно убрать

2024-11-24 15:38 UTC, pocahontassss commented on src/app/users.service.ts
> +    userSubjects = new BehaviorSubject<User[]>([]);
Сущности rxjs помечаем с помощью $
Также нужно создать observable от subject, к которому мы и будем обращаться вне сервиса

2024-11-24 15:38 UTC, pocahontassss commented on src/app/todos.service.ts
> +    todos: Todo [] = [];
Аналогично с юзерами

2024-11-24 15:39 UTC, pocahontassss requested changes

2024-11-24 15:39 UTC, pocahontassss commented on src/app/todos-list/todos-list.component.html
> +    <div *ngFor="let todo of todosService.todoSubjects | async">
Здесь должны обращаться к обсерваблу

2024-11-24 15:39 UTC, pocahontassss commented on src/app/users-list/users-list.component.html
> +    <div *ngFor="let user of usersService.userSubjects | async">
Аналогично

2024-11-24 15:39 UTC, pocahontassss commented on src/app/users-list/users-list.component.ts
> +}
Где типизация? Почему интерфейс неполный?

2024-12-13 14:26 UTC, YusupOzdoyev requested changes

2024-12-13 14:26 UTC, YusupOzdoyev commented on src/app/app.component.ts
> +// const time = new Date() .getTime();
удали комментарии во всем проекте

2024-12-13 14:26 UTC, YusupOzdoyev commented on src/app/app.routes.ts
> +        path: 'head',
задай так же пустой роут по умолчанию ""

2024-12-13 14:26 UTC, YusupOzdoyev commented on src/app/app.routes.ts
> +import { LocationComponent } from './components/location/location.component';
здесь ' '  одинарные кавычки а ниже в других компонентах " "
двойные. Сделай в импортах везде одинаково

2024-12-13 14:26 UTC, YusupOzdoyev commented on src/app/app.routes.ts
> +        path: 'foot',
что за путь foot ?
и остальные тоже для чего ?

2024-12-13 14:26 UTC, YusupOzdoyev commented on src/app/users-list/users-list.component.ts
>  const consoleResponse = (response: any) => {
удали

2024-12-13 14:26 UTC, YusupOzdoyev commented on src/app/users-list/users-list.component.ts
> +            open: function (EditUserDialogComponent: EditUserDialogComponent, arg1: { data: { user: User; }; }): unknown {
этот код так же на 14строке. не понял

2024-12-13 14:26 UTC, YusupOzdoyev commented on src/app/users-list/users-list.component.ts
> +    editUser(user: any) {
типизируй

2024-12-20 08:33 UTC, Ridook commented on src/app/components/header/header.component.ts
>      styleUrl: './header.component.scss',
добавь OnPush

2024-12-20 13:11 UTC, closed without merging