Routing homework
RYAZHAPOVILNUR/mentoring-base pull request #250
Opened 2024-11-25 17:14 UTC by Radmil11

@radmilahi

2024-11-25 17:55 UTC, pocahontassss approved these changes, later dismissed

2024-11-25 17:55 UTC, pocahontassss commented on src/app/app.routes.ts
> +  }
Проблемка с форматированием

2024-11-25 17:57 UTC, pocahontassss requested changes
А где сами компоненты, указанные в роутинге? Не вижу их в проекте

2024-11-25 18:16 UTC, pocahontassss requested changes

2024-11-25 18:16 UTC, pocahontassss commented on src/app/components/users/users.component.ts
> +}
Здесь проблема с форматированием, начиная с 22 строки

2024-11-25 18:16 UTC, pocahontassss commented on src/app/components/users/users.component.ts
> +const apiservise = '';
Это лишнее

2024-11-25 18:16 UTC, pocahontassss commented on src/app/components/users/users.component.html
> +</div>
Лучше навесить класс и стилизовать в scss, нежели прямо в шаблоне

2024-11-30 12:16 UTC, Radmil11 commented on src/app/components/users/users.component.ts
> +const apiservise = '';
если это удаляю ошибки выдает

2024-11-30 12:38 UTC, Radmil11 commented on src/app/app.routes.ts
> +  }
сделал

2024-11-30 12:38 UTC, Radmil11 commented on src/app/components/users/users.component.ts
> +}
сделал

2024-11-30 12:40 UTC, Radmil11 commented on src/app/components/users/users.component.html
> +</div>
навесил класс в scss

2024-11-30 15:46 UTC, pocahontassss approved these changes

2024-11-30 15:46 UTC, closed without merging