ngrx-todos
RYAZHAPOVILNUR/mentoring-base pull request #252
Opened 2024-11-26 11:35 UTC by shepherd1422

![ngrx](https://github.com/user-attachments/assets/59a129a7-ed86-4a20-b379-9c584e17de33)

2024-11-26 20:23 UTC, pocahontassss requested changes

2024-11-26 20:23 UTC, pocahontassss commented on src/app/components/home/todos-list.component/todos-list.component.component.ts
> +    })
Давно пора типизировать responce)

2024-11-26 20:23 UTC, pocahontassss commented on src/app/components/home/users-list/users-list.component.ts
>    }
Аналогично

2024-11-26 20:23 UTC, pocahontassss commented on src/app/components/home/users-list/users-list.component.ts
>      });
Нам при создании юзера, не нужно в диалоговое окно прокидывать никаких данных

2024-11-30 00:17 UTC, shepherd1422 commented on src/app/components/home/users-list/users-list.component.ts
>    }
сделал

2024-11-30 00:17 UTC, shepherd1422 commented on src/app/components/home/todos-list.component/todos-list.component.component.ts
> +    })
сделал

2024-11-30 00:17 UTC, shepherd1422 commented on src/app/components/home/users-list/users-list.component.ts
>      });
сделал

2024-12-03 18:01 UTC, pocahontassss approved these changes

2024-12-03 18:01 UTC, closed without merging