Task 14
RYAZHAPOVILNUR/mentoring-base pull request #266
Opened 2024-12-01 16:31 UTC by KoznovDm

https://t.me/Alexsandrovichhhhh

2024-12-02 07:54 UTC, pocahontassss requested changes

2024-12-02 07:54 UTC, pocahontassss commented on src/app/users-list/users-list.components.ts
> +        }
Здесь можно передать просто  user, без объекта и ...

2024-12-02 07:54 UTC, pocahontassss commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.html
> +    <button mat-raised-button color="primary" class="add-user" [mat-dialog-close]="userWithUpdatedFieilds"  [disabled]="formUser.invalid">
https://www.youtube.com/watch?v=WTm6VoPu-U8
[1:12:00](https://www.youtube.com/watch?v=WTm6VoPu-U8&t=4320s) - [1:17:20](https://www.youtube.com/watch?v=WTm6VoPu-U8&t=4640s) — Почему нельзя делать привязку через [mat-dialog-close]="submitForm()"

2024-12-02 07:59 UTC, pocahontassss requested changes

2024-12-02 07:59 UTC, pocahontassss commented on src/app/users.service.ts
> +    }
Нельзя делать отрисовку UI в сервисах. Сервис отвечает за хранение данных и бизнес-логику, а не за то, что бы отрисовывать какие-то мат бары и так далее. Это должно быть вынесено на уровне компонента

2024-12-02 07:59 UTC, pocahontassss commented on src/app/users-list/users-list.components.ts
> +
А что за юзера мы тут передаем? Это же создания пользователя и на данном этапе его просто не существует

2024-12-02 07:59 UTC, pocahontassss commented on src/app/users-list/users-list.components.ts
> +  user!: User;
Этот инпут здесь не нужен, он в user-card прописывается

2024-12-02 07:59 UTC, pocahontassss commented on src/app/users-list/delete-user-dialog/delete-user-dialog.component.ts
> +  constructor(public dialogRef: MatDialogRef<DeleteUserDialogComponent>) {}
Через inject функцию это делается, а не через конструктор. Это старый способ написания, пользуйся новым)

2024-12-02 07:59 UTC, pocahontassss commented on src/app/create-user-form/create-user-form.component.ts
> + readonly data =inject<{ user: User }>(MAT_DIALOG_DATA);
Здесь мы никаких данных не получаем, юзера не существует еще

2024-12-02 07:59 UTC, pocahontassss commented on src/app/create-user-form/create-user-form.component.ts
> +}}
Аналогично. Через inject функцию. И конструктор должен всегда находиться вверху, в начале класса

2024-12-02 07:59 UTC, pocahontassss commented on src/app/create-user-form/create-user-form.component.ts
> +  }
1.   event.preventDefault(); - это уже js какой-то пошел) лишняя строка
2. Незачем делать проверку на валидность. Если кнопка невалидна - ты не сможешь на нее нажать, никогда.

2024-12-02 18:31 UTC, KoznovDm commented
привязаю событие отправки формы с помощью (ngSubmit)="submitForm()" к тегу <form>, тогда корректно обрабатывается отправка формы.

2024-12-05 23:24 UTC, pocahontassss approved these changes

2024-12-05 23:24 UTC, closed without merging