Feat add service, @input, @output
RYAZHAPOVILNUR/mentoring-base pull request #270
Opened 2024-12-03 15:37 UTC by Ildar-Safin

Выполнил дз по 10 уроку. Сервисы, передача данных и обработка событий через @Input, @Output
tg: @S_ildar_Abd

2024-12-04 07:38 UTC, pocahontassss requested changes

2024-12-04 07:38 UTC, pocahontassss commented on src/app/users-list/users-list.component.html
> +<div style="display: flex; width: 100%; flex-wrap: wrap">
Лучше здесь никогда не писать стили. Всегда пишем их в классах в  scss файле

2024-12-04 07:38 UTC, pocahontassss commented on src/app/users-list/user-card/user-card.component.ts
> +  user: any;
Протипизировать

2024-12-04 07:38 UTC, pocahontassss commented on src/app/todo-list/todos-list.component.ts
> +    this.todos = this.todos.filter(
Типизировать

2024-12-04 07:38 UTC, pocahontassss commented on src/app/todo-list/todos-list.component.html
> +<div style="display: flex; width: 100%; flex-wrap: wrap;">
Аналогично. Здесь не стилизуем

2024-12-04 07:38 UTC, pocahontassss commented on src/app/todo-list/todo-card/todo-card.component.ts
> +
Типизация

2024-12-05 20:38 UTC, Ildar-Safin commented
1. Перенес стили  scss файлы
2. Попробовал сделать типизацию, правильно или нет не знаю, просьба дать обратную связь.

2024-12-05 23:21 UTC, anatolyeviich requested changes

2024-12-05 23:21 UTC, anatolyeviich commented on src/app/users-list/user-card/user-card.component.ts
> +  user: User | undefined;
User у тебя undefined не будет. Ошибка уйдет, если ты напишешь "user:! User", так ты скажешь ts'y, что данные будут инициализированы позже

2024-12-05 23:21 UTC, anatolyeviich commented on src/app/users-list/user-card/user-card.component.ts
> +
В идеале - вынести это в отдельный файл нужно. user-interface.ts

2024-12-05 23:21 UTC, anatolyeviich commented on src/app/users-list/user-card/user-card.component.html
> +  <button class="click" (click)=onDeleteUser(user!.id)>УДАЛИТЬ ЮЗЕРА</button>
А вот здесь просто user.id

2024-12-05 23:21 UTC, anatolyeviich commented on src/app/todo-list/todo-card/todo-card.component.ts
> +  todo: Todo | undefined;
Аналогично, todo!

2024-12-05 23:21 UTC, anatolyeviich commented on src/app/todo-list/todo-card/todo-card.component.ts
> +}
Вынести

2024-12-05 23:21 UTC, anatolyeviich commented on src/app/todo-list/todo-card/todo-card.component.html
> +  <button (click)=onDeleteTodo(todo!.id)>УДАЛИТЬ ЗАДАЧУ</button>
просто todo.id

2024-12-06 08:22 UTC, Ildar-Safin commented
интерфейс переписал по новой, User  и Todo в один файл записал и потом с этого файла делал импортировал. Пробовал добавить изменения уже в опубликованный коммит, не получилось по всей видимости, значит что-то делал не так.

2024-12-06 20:26 UTC, pocahontassss approved these changes

2024-12-06 20:26 UTC, closed without merging