completed Input output
RYAZHAPOVILNUR/mentoring-base pull request #291
Opened 2024-12-12 11:18 UTC by Radmil11

@radmilahi

2024-12-12 15:48 UTC, pocahontassss requested changes

2024-12-12 15:48 UTC, pocahontassss commented on src/app/components/todos/todo-card/todo-card.component.ts
> +  todo: any
Типизация нужна

2024-12-12 15:48 UTC, pocahontassss commented on src/app/components/todos/todos.component.ts
> +  deleteTodo(id: any) {
Типизация

2024-12-12 15:48 UTC, pocahontassss commented on src/app/components/todos/todos.component.ts
> +  }
Типизация

2024-12-12 15:48 UTC, pocahontassss commented on src/app/components/users/user-card/user-card.component.html
> +  <p>{{ $any(user).company.name }}</p>
Здесь просто  написать user.name и тд

2024-12-12 15:48 UTC, pocahontassss commented on src/app/components/users/user-card/user-card.component.scss
> +  border-radius: px;
?? Можно убрать

2024-12-12 15:48 UTC, pocahontassss commented on src/app/components/users/user-card/user-card.component.ts
> +  user: any;
Типизация

2024-12-12 15:48 UTC, pocahontassss commented on src/app/components/users/user-card/user-card.component.ts
> +  }
Лишние пробелы на 13 и 15

2024-12-12 15:48 UTC, pocahontassss commented on src/app/components/users/users.component.ts
> +    this.usersApiService.getUsers().subscribe((response: any) => {
Типизация

2024-12-12 15:48 UTC, pocahontassss commented on src/app/todos-api.service.ts
> +  }
Типизировать дженериком

2024-12-12 15:48 UTC, pocahontassss commented on src/app/users-api.service.ts
> +
Это удалить

2024-12-12 15:48 UTC, pocahontassss commented on src/app/users-api.service.ts
> +  }
Это тоже протипизировать дженериком

2024-12-17 18:46 UTC, Radmil11 commented on src/app/components/users/user-card/user-card.component.scss
> +  border-radius: px;
Это дизайн кнопки сделал по заданию, в отдельный класс вывел в scss

2024-12-17 20:31 UTC, pocahontassss approved these changes

2024-12-17 20:31 UTC, closed without merging