Update guard
RYAZHAPOVILNUR/mentoring-base pull request #294
Opened 2024-12-14 11:35 UTC by RuslanDev777

Исправил проект завершил гварды

2024-12-14 14:34 UTC, Ridook commented on src/app/content/content.component.scss
> +  // height: 430;
комментарии не оставлять

2024-12-14 14:34 UTC, Ridook commented on src/app/content/content.component.scss
> +  // height: 430;
еще сверху убрать и снизу

2024-12-14 14:34 UTC, Ridook commented on src/app/create-todos-form/create-todo-form.ts
> +export function comletedValidator(): ValidatorFn {
вынеси валидатор в другой файл

2024-12-14 14:34 UTC, Ridook commented on src/app/home/home.component.ts
> +  logout() {
тут тоже укажи типы для функций, как ниже указал для isAdmin

2024-12-14 14:34 UTC, Ridook commented on src/app/todos-list/todos-list.component.ts
> +      .subscribe((responce: Todos[]) => this.todosService.setTodos(responce));
отписки нет

2024-12-14 14:34 UTC, Ridook commented on src/app/users-list/create-user-dialog/create-user-dialog.component.scss
> +//   // transition: border-color 0.3s ease, box-shadow 0.3s ease;
удалить если не нужно

2024-12-14 14:34 UTC, Ridook commented on src/app/users-list/create-user-dialog/create-user-dialog.component.ts
> +      // id: new Date().getTime(),
комм

2024-12-14 14:34 UTC, Ridook commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.scss
> +  //   justify-content: center;
коммы

2024-12-14 14:34 UTC, Ridook commented on src/app/users-list/user-card/user-card.component.scss
> +
коммы

2024-12-14 14:34 UTC, Ridook commented on src/app/users-list/user-card/user-card.component.ts
> +      console.log('Модалка закрылась', editResult);
консоль убрать

2024-12-14 14:34 UTC, Ridook commented on src/app/users-list/users-list.component.ts
> +  user: any;
any

2024-12-14 14:34 UTC, Ridook commented on src/app/users-list/users-list.component.ts
> +      .subscribe((responce: User[]) => this.usersService.setUsers(responce));
нет отписки

2024-12-14 14:34 UTC, Ridook commented on src/app/users-list/users-list.component.ts
> +    console.log(formData);
консоль

2024-12-14 14:34 UTC, Ridook commented on src/app/users-list/users-list.component.ts
> +      horizontalPosition: 'right', // Расположение по горизонтали
комментарии

2024-12-16 11:58 UTC, YusupOzdoyev requested changes

2024-12-16 11:58 UTC, YusupOzdoyev commented on src/app/app.config.ts
> +        // subscriptSizing: 'dynamic', //убирает поля которые открываются в верстке для ошибок
удали

2024-12-16 11:58 UTC, YusupOzdoyev commented on src/app/content/content.component.html
> +<button (click)="isShowMan = !isShowMan">Скрыть/показать мужика</button>
{{ isShowMan : "скрыть" ? "показать" }}

2024-12-16 11:58 UTC, YusupOzdoyev commented on src/app/interfaces/user.interface.ts
> +export interface UserForm extends User {
создай для каждой сущности отдельный файл и положи в папке

2024-12-16 11:58 UTC, YusupOzdoyev commented on src/app/todos-list/todo-card/todo-card.component.ts
> +  todo: any;
типизируй

2024-12-16 11:58 UTC, YusupOzdoyev commented on src/app/todos-list/todos-list.component.scss
> +  //   max-width: calc(33.333% - 40px);
удали комменты везде в проекте

2024-12-16 11:58 UTC, YusupOzdoyev commented on src/app/interfaces/todos.interface.ts
> +export interface Todos {
почему в множ числе ?

2024-12-16 11:58 UTC, YusupOzdoyev commented on src/app/todos-list/todos-list.component.ts
> +  createTodo(dataFormTodo: Todos) {
тут Todos вводит в заблуждение

2024-12-16 11:58 UTC, YusupOzdoyev commented on src/app/todos.service.ts
> +  createTodo(todo: any) {
типизируй

2024-12-26 10:51 UTC, closed without merging