start js
RYAZHAPOVILNUR/mentoring-base pull request #304
Opened 2024-12-17 11:19 UTC by dfdev2

2024-12-17 11:20 UTC, dfdev2 commented
start JS

2024-12-18 13:09 UTC, YusupOzdoyev requested changes

2024-12-18 13:09 UTC, YusupOzdoyev commented on src/app/components/footer/footer.component.scss
> +  // .footer-bottom__ask
удали комменты везде во всем проекте

2024-12-18 13:25 UTC, dfdev2 commented on src/app/components/footer/footer.component.scss
> +  // .footer-bottom__ask
сделал

2024-12-20 17:17 UTC, Ridook commented on src/app/components/todos/todo/todo.component.ts
> +  styleUrl: './todo.component.scss',
OnPush

2024-12-20 17:17 UTC, Ridook commented on src/app/components/todos/todo/todo.component.ts
> +  todoItem: any;
убрать any

2024-12-20 17:17 UTC, Ridook commented on src/app/components/todos/todos.component.ts
> +  styleUrl: './todos.component.scss',
OnPush

2024-12-20 17:17 UTC, Ridook commented on src/app/components/todos/todos.component.ts
> +    this.todoApiService.getTodos().subscribe((response: any) => {
отписка, и any убрать

2024-12-20 17:17 UTC, Ridook commented on src/app/components/users-list/usersList.component.ts
> +    this.usersApiService.getUsers().subscribe((response: any) => {
any и onPush выше

2024-12-20 17:22 UTC, Ridook commented on src/app/components/todos/todos.component.ts
> +  delTodo = (id: number) => {
дать нормальное название

2024-12-21 16:57 UTC, YusupOzdoyev commented on src/app/Interfases.ts
> +interface Geo {
раздели интерфейсы иразмести их в отдельные файлы

2024-12-22 08:37 UTC, dfdev2 commented on src/app/Interfases.ts
> +interface Geo {
у меня инетфейсы все отдельно этот файл у меня как шаблон там пример интерфейсов он не куда не подключен

2024-12-23 08:41 UTC, YusupOzdoyev commented on src/app/components/create-task-form/create-task-form.component.ts
> +  // Отправка данных наружу
удали комменты везде во всем проекте

2024-12-23 08:41 UTC, YusupOzdoyev commented on src/app/components/create-task-form/create-task-form.component.ts
> +  onButtonClick(): void {
удали консоль логи во всем проеткте

2024-12-23 08:41 UTC, YusupOzdoyev commented on src/app/components/create-user-form/create-user-form.component.ts
> +    this.form.valueChanges.subscribe((formValue) => console.log(formValue));
удали

2024-12-23 08:41 UTC, YusupOzdoyev commented on src/app/components/todos/todos-list.component.ts
> +  changeDetection: ChangeDetectionStrategy.OnPush,
changeDetection: ChangeDetectionStrategy.OnPush,
пропиши во всех компонентах в проекте

2024-12-23 08:41 UTC, YusupOzdoyev commented on src/app/components/todos/todos-list.component.ts
> +    this.todoApiService.getTodos().subscribe((response: Todo[]) => {
делай это в ngOnChanges и про отписку не забывай. почисти конструктор

2024-12-23 08:41 UTC, YusupOzdoyev commented on src/app/components/users-list/users-list.component.ts
> +    this.usersApiService.getUsers().subscribe((response: User[]) => {
ngOnChanges, почисти конструуктор.
отпишись

2024-12-23 08:41 UTC, YusupOzdoyev commented on src/app/Interfases.ts
> +interface Geo {
удали

2024-12-23 11:11 UTC, dfdev2 commented on src/app/components/todos/todos-list.component.ts
> +    this.todoApiService.getTodos().subscribe((response: Todo[]) => {
ngOnChanges это мы еще не проходили

2024-12-23 11:12 UTC, dfdev2 commented on src/app/components/todos/todos-list.component.ts
> +  changeDetection: ChangeDetectionStrategy.OnPush,
сделал

2024-12-23 11:12 UTC, dfdev2 commented on src/app/components/create-task-form/create-task-form.component.ts
> +  // Отправка данных наружу
сделал

2024-12-23 11:14 UTC, dfdev2 commented on src/app/Interfases.ts
> +interface Geo {
сделал

2024-12-23 11:14 UTC, dfdev2 commented on src/app/components/create-task-form/create-task-form.component.ts
> +  onButtonClick(): void {
сделал

2024-12-23 11:14 UTC, dfdev2 commented on src/app/components/create-user-form/create-user-form.component.ts
> +    this.form.valueChanges.subscribe((formValue) => console.log(formValue));
сделал

2024-12-23 11:15 UTC, dfdev2 commented on src/app/components/users-list/users-list.component.ts
> +    this.usersApiService.getUsers().subscribe((response: User[]) => {
про отписку не проходили на досуге посмотрю

2024-12-25 13:57 UTC, YusupOzdoyev commented on src/app/services/todos.servece.ts
> +    // next типо заменяет =
удали все комменты

2024-12-25 13:57 UTC, YusupOzdoyev commented on src/assets/js/erroe.ts
> +<div class="create-user__name">
название файла кривое какое-то

2024-12-25 13:59 UTC, dfdev2 commented on src/app/services/todos.servece.ts
> +    // next типо заменяет =
сделал

2024-12-25 14:00 UTC, dfdev2 commented on src/assets/js/erroe.ts
> +<div class="create-user__name">
такие названия в методологии БЭМ

2024-12-25 14:01 UTC, dfdev2 commented on src/assets/js/erroe.ts
> +<div class="create-user__name">
но этот фойл я просто добавил чтобы код не потерять потом забыл удалить уже удаляю

2024-12-26 10:51 UTC, closed without merging