finished website layout
RYAZHAPOVILNUR/mentoring-base pull request #313
Opened 2024-12-20 13:18 UTC by Mir4ikqwe19

2024-12-20 13:19 UTC, YusupOzdoyev requested changes

2024-12-20 13:19 UTC, YusupOzdoyev commented on src/styles.scss
> +     ========================================================================== */
удали комменты по всему проекту

2024-12-20 13:27 UTC, Mir4ikqwe19 commented on src/styles.scss
> +     ========================================================================== */
окей, а в остальном принято?

2024-12-23 23:15 UTC, pocahontassss approved these changes

2024-12-23 23:15 UTC, closed without merging