Todos and rxjs
RYAZHAPOVILNUR/mentoring-base pull request #55
Opened 2024-09-24 19:19 UTC by Safarov12

Сделала юзерам сервис и повторила все для задач

2024-09-25 14:11 UTC, pocahontassss commented on src/app/user-list/user-list.component.html
> +  <div *ngFor="let item of usersService.userSubject$ | async">
Ты создала поток данных userSubject. После ты должна была сделать его неизменяемым, то-есть применить оператор .asObservable, и потом с этим новым потоком работать, а так ты обращаешься к сабджекту.

2024-09-25 14:11 UTC, pocahontassss commented on src/app/todos-list/todos-card/todos-card.component.ts
>    todo: any
Нужно протипизировать пришедшие данные через инпут

2024-09-25 14:11 UTC, pocahontassss commented on src/app/todos-list/todos-list.component.html
> +  <div *ngFor="let todo of todosService.todoSubject$ | async">
Аналогично, как и с пользователями, нужно обращаться к обсерваблу

2024-09-25 14:11 UTC, pocahontassss commented on src/app/todo.service.ts
> +  deleteTodo (id: any) {
Нужно протипизировать

2024-09-26 01:48 UTC, RYAZHAPOVILNUR commented
я тоже проверил, согласен с комментами Владислава

2024-09-30 09:56 UTC, pocahontassss requested changes

2024-09-30 09:56 UTC, pocahontassss commented on src/app/user-list/user-list.component.ts
> +    this.usersService.createUser({
Нужно протипизировать

2024-09-30 09:56 UTC, pocahontassss commented on src/app/todos-list/todos-list.component.ts
> +    this.todosService.createTodo({
Нужно протипизировать

2024-09-30 15:10 UTC, pocahontassss requested changes

2024-09-30 15:10 UTC, pocahontassss commented on src/app/todos-list/todos-list.component.ts
> +    this.todosService.createTodo({
Нужна типизация

2024-09-30 15:10 UTC, pocahontassss commented on src/app/user-list/user-list.component.ts
> +      id: new Date().getTime(),
Нужна типизация

2024-10-02 13:32 UTC, pocahontassss requested changes
Задачи протипизировала, а юзеров?)

2024-10-02 14:11 UTC, pocahontassss approved these changes

2024-10-02 14:11 UTC, closed without merging