Todos
RYAZHAPOVILNUR/mentoring-base pull request #60
Opened 2024-09-25 16:30 UTC by Di-Zi

Added branch todos

2024-09-26 02:00 UTC, RYAZHAPOVILNUR requested changes

2024-09-26 02:00 UTC, RYAZHAPOVILNUR commented on src/app/todos-list/todos-list.component.ts
> +        userId: number;
огромные отступы, такого быть не должно

2024-09-26 02:00 UTC, RYAZHAPOVILNUR commented on src/app/todos-list/todos-list.component.ts
> +    }
фигурная скобка должна быть без отступов

2024-09-26 02:00 UTC, RYAZHAPOVILNUR commented on src/app/todos-list/todos-list.component.ts
> +
лишняя пустая строка

2024-09-26 02:00 UTC, RYAZHAPOVILNUR commented on src/app/todos-list/todos-list.component.ts
> +
лишняя пустая строка

2024-09-26 02:00 UTC, RYAZHAPOVILNUR commented on src/app/todos-list/todos-list.component.ts
> +            this.todosService.setTodos(response);
дальше проверять не буду, сначала исправь форматирование

2024-09-26 02:01 UTC, RYAZHAPOVILNUR commented
сделать форматирование, иначе невозможно читать код

добавить описание чтобы можно было тебя найти в TG

2024-09-26 02:01 UTC, RYAZHAPOVILNUR commented
@Di-Zi

2024-09-30 21:38 UTC, pocahontassss approved these changes

2024-09-30 21:38 UTC, pocahontassss commented on src/app/create-user-form/create-user-form.component.ts
> +}
На 12 и 25 - лишние пустые строки
Не забываем подчищать комментарии (с 30 по 35)

2024-09-30 21:38 UTC, pocahontassss commented on src/app/create-user-form/create-user-form.component.scss
> +}
между классами (между 3 и 4 строками) должна быть пустая строка

2024-09-30 21:40 UTC, pocahontassss requested changes
Нужно исправить форматирование (сообщение Ильнура + мои сообщения)

2024-10-08 19:55 UTC, pocahontassss requested changes

2024-10-08 19:55 UTC, pocahontassss commented on src/app/create-todo-form/create-todo-form.component.html
> +    <form style="display: flex; flex-direction: column;" [formGroup]="form" (ngSubmit)="submitForm()">
Стили вынести в классы

2024-10-08 19:55 UTC, pocahontassss commented on src/app/create-todo-form/create-todo-form.component.scss
> +    color: red;
Цвет указываем всегда в хэше или rgb

2024-10-08 19:55 UTC, pocahontassss commented on src/app/create-user-form/create-user-form.component.html
> +        </button> -->
Не забываем чистить закоментированный код. А он у тебя по всему проекту

2024-10-08 19:55 UTC, pocahontassss commented on src/app/create-todo-form/create-todo-form.component.html
> +        </button> -->
Аналогично подчистить

2024-10-08 19:55 UTC, pocahontassss commented on src/app/users.service.ts
> +        // )
И тут почистить

2024-10-08 19:55 UTC, pocahontassss commented on src/app/users-list/users-list.component.ts
> +    public createUser(formData: any) {
Нужна типизация

2024-10-08 19:55 UTC, pocahontassss commented on src/app/users-list/users-list.component.ts
> +      }
Также пора вынести интерфейсы в отдельную папку interfaces, в которой:
1 файл - user-interfaces.ts, в котором находятся все интерфейсы, связанные с сущностью пользоваталей.
2 файл - todo-interfaces.ts, аналогично выше

2024-11-15 17:22 UTC, pocahontassss requested changes
1. Чистка комментариев
2. Форматирование
3. Исправить ошибки, указанные в комментариях

2024-11-15 17:22 UTC, pocahontassss commented on src/app/users-list/users-list.component.html
>      <div *ngFor="let item of usersService.users$ | async">
1. Чистим комментарии
2. Стили прописываем в scss файле.

2024-11-15 17:22 UTC, pocahontassss commented on src/app/users-list/users-list.component.html
>      <div *ngFor="let item of usersService.users$ | async">
*ngFor="let item of usersService.users$ | async"> 

let user of users

2024-11-15 17:22 UTC, pocahontassss commented on src/app/users-list/create-user-dialog/create-user-dialog.component.ts
> +
Почистить комментарии

2024-11-15 17:22 UTC, pocahontassss commented on src/app/users-list/create-user-dialog/create-user-dialog.component.html
> +            </button>
https://www.youtube.com/watch?v=WTm6VoPu-U8/

[1:12:00](https://www.youtube.com/watch?v=WTm6VoPu-U8&t=4320s) - [1:17:20](https://www.youtube.com/watch?v=WTm6VoPu-U8&t=4640s) — Почему нельзя делать привязку через [mat-dialog-close]="submitForm()"

2024-11-15 17:22 UTC, pocahontassss commented on src/app/user.service.ts
> +
Модификатор доступа

2024-11-15 17:22 UTC, pocahontassss commented on src/app/todos-list/todos-list.component.ts
> +
Модификатор доступа + типизацию (через дженерик)

2024-11-15 17:22 UTC, pocahontassss commented on src/app/admin-dialog/admin-dialog.component.ts
> +    // }
Почистить комменты

2024-11-15 17:22 UTC, pocahontassss commented on src/app/app.routes.ts
> +    }
Накинуть гвард

2024-11-15 17:22 UTC, pocahontassss commented on src/app/directives/red.directive.ts
> +    //     this.elementRef.nativeElement.style.backgroundColor = 'red';
Конструктор выносим наверх, Комментарии чистим

2024-11-15 17:22 UTC, pocahontassss commented on src/app/guards/is-admin.guard.ts
> +    // )
Чистка

2024-11-15 17:22 UTC, pocahontassss commented on src/app/header/header.component.html
> +              </nav>
Чистка

2024-11-15 17:22 UTC, pocahontassss commented on src/app/header/header.component.ts
> +
Форматирование

2024-11-15 17:22 UTC, pocahontassss commented on src/app/pipes/date.pipe.ts
> +
Чистка

2024-11-15 17:22 UTC, pocahontassss commented on src/app/pipes/slice.pipe.ts
> +}
Форматирование

2024-11-29 08:59 UTC, pocahontassss approved these changes

2024-11-29 08:59 UTC, pocahontassss commented on src/app/users-list/store/user.reducer.ts
> +        })
Можно было написать в одну строку условным тернарным оператором

2024-11-29 08:59 UTC, pocahontassss commented on src/app/todos-list/store/todo.reducer.ts
> +        })
Аналогично юзерам

2024-11-29 09:00 UTC, closed without merging