сделал задачи  @input,  @output
RYAZHAPOVILNUR/mentoring-base pull request #61
Opened 2024-09-25 21:30 UTC by ibragim111

2024-09-26 01:55 UTC, RYAZHAPOVILNUR requested changes

2024-09-26 01:55 UTC, RYAZHAPOVILNUR commented on src/app/todos-list/todos-list.component.ts
> +@Injectable()
не принимаю домашку из-за того, что декоратор Injectable над компонентом, переделать обязательно

2024-09-26 01:55 UTC, RYAZHAPOVILNUR commented on src/app/todos-list/todos-list.component.ts
> +  }
пустой строки не хватает

2024-09-26 01:55 UTC, RYAZHAPOVILNUR commented on src/app/todos-list/todos-list.component.ts
> +}
пустой строки не хватает

2024-09-26 01:55 UTC, RYAZHAPOVILNUR commented on src/app/todos-list/todos-list.component.ts
> +  todos: Todo[] = [];
пустой строки не хватает

2024-09-26 01:55 UTC, RYAZHAPOVILNUR commented on src/app/users-list/user-card/user-card.component.ts
> +  user: any;
нужно создать интерфейс и указать здесь вместо any

2024-09-26 01:55 UTC, RYAZHAPOVILNUR commented on src/app/users-list/users-list.component.scss
> +}
между блоками не хватает пустых строк

2024-09-26 01:55 UTC, RYAZHAPOVILNUR commented on src/app/users-list/users-list.component.ts
> +@Injectable()
уволен за такое 😁

срочно удалить декоратор @Injectable

2024-09-26 01:55 UTC, RYAZHAPOVILNUR commented on src/app/users-list/users-list.component.ts
> +  }
пустой строки не хватает

2024-09-28 16:14 UTC, pocahontassss commented on src/app/todos-list/todos-list.component.ts
>  export class TodosListComponent {
Здесь не хватает пустой строки (между 19-20 строками)

2024-09-28 16:15 UTC, closed without merging