Rx js домашка
RYAZHAPOVILNUR/mentoring-base pull request #64
Opened 2024-09-26 15:44 UTC by AzatGareev

@G_Venerka_A

2024-09-26 16:06 UTC, pocahontassss requested changes

2024-09-26 16:06 UTC, pocahontassss commented on src/app/users-list/users-list.component.ts
>  export interface User {
У тебя уже есть такой интерфейс в homerwork.ts. Ты его продублировала. Советую вынести его в отдельный файл и импортировать там, где тебе нужно его использовать

2024-09-26 16:06 UTC, pocahontassss commented on src/app/todo.service.ts
> +    todosSubject$ = new BehaviorSubject<Todo[]>([]);
Ты создала поток данных userSubject. После ты должна была сделать его неизменяемым, то-есть применить оператор .asObservable, и потом с этим новым потоком работать, а так ты обращаешься к сабджекту.

2024-09-26 16:06 UTC, pocahontassss commented on src/app/todos-list/todos-list.component.html
> +    <div *ngFor="let todo of todosService.todosSubject$ | async">
Здесь соответственно обращаемся к обсерваблу, а не к сабджекту

2024-09-26 16:06 UTC, pocahontassss commented on src/app/todos-list/todos-card/todos-card.component.ts
>      todo: any
Не протипизировала входные данные

2024-09-26 16:06 UTC, pocahontassss commented on src/app/todos-list/todos-card/todos-card.component.ts
> +    deleteTodos = new EventEmitter()
Правильнее deleteTodo (удалить задачу), а не todos (задачи)

2024-09-28 12:48 UTC, AzatGareev commented on src/app/todos-list/todos-card/todos-card.component.ts
>      todo: any
+

2024-09-28 12:48 UTC, AzatGareev commented on src/app/todos-list/todos-list.component.html
> +    <div *ngFor="let todo of todosService.todosSubject$ | async">
+

2024-09-28 12:48 UTC, AzatGareev commented on src/app/todo.service.ts
> +    todosSubject$ = new BehaviorSubject<Todo[]>([]);
+

2024-09-28 12:48 UTC, AzatGareev commented on src/app/users-list/users-list.component.ts
>  export interface User {
+

2024-09-28 12:50 UTC, AzatGareev commented on src/app/todos-list/todos-card/todos-card.component.ts
> +    deleteTodos = new EventEmitter()
+

2024-09-28 16:20 UTC, closed without merging