added_form_builder
RYAZHAPOVILNUR/mentoring-base pull request #72
Opened 2024-09-29 21:04 UTC by rabiulawal1422

<img width="1680" alt="Screenshot 2024-09-30 at 6 04 02 AM" src="https://github.com/user-attachments/assets/5e797592-635a-4fc1-a3a5-3fc6e54faa88">

2024-09-30 10:27 UTC, pocahontassss requested changes
Исправить все моменты @rabiulawal1422

2024-09-30 10:27 UTC, pocahontassss commented on src/app/users-list/users-list.component.ts
> +  public createUser(formData: any) {
Нужно протипизировать

2024-09-30 10:27 UTC, pocahontassss commented on src/app/users-list/user__interface.ts
Не очень корректное название файла. todo ты создал через один дефис, здесь используешь два нижних подчеркивания. Советую называть файлы в едином стиле

2024-09-30 10:27 UTC, pocahontassss commented on src/app/users-list/user-card/user-card.component.ts
> +    user: any
Нужна типизация

2024-09-30 10:27 UTC, pocahontassss commented on src/app/todos-list.component/todos-list.component.component.ts
> +  public createTodos(formData: any) {
Нужна типизация

2024-09-30 10:27 UTC, pocahontassss commented on src/app/todos-list.component/todos-list.component.component.scss
> +  font-family: Inter;
1 раз прописать в глобальных классах и не придется в каждом компоненте писать данное свойство

2024-09-30 10:27 UTC, pocahontassss commented on src/app/todos-list.component/todos-list.component.component.html
> +      [todo]="el"
Семантически корректнее будет написать todo, а не el. Таким образом код становится легче и понятнее.

2024-09-30 10:27 UTC, pocahontassss commented on src/app/todos-list.component/todo-card/todo-card.component.ts
> +  todo: any;
Нет типизации

2024-09-30 10:27 UTC, pocahontassss commented on src/app/create-user-form/create-user-form.component.scss
> +  width: 150px;
Не хватает пустой строки.
Лучше не допускать стилизацию по тегам, для этого есть айди, классы

2024-09-30 10:27 UTC, pocahontassss commented on src/app/create-todos-form/create-todos-form.component.scss
> +  margin-top: 20px;
Аналогично, нет пустой строки + не стилизуем по тегу

2024-09-30 10:27 UTC, pocahontassss commented on src/app/create-todos-form/create-todos-form.component.ts
> +  });
Здесь стоит валидатор на то, что если букв < 3 = форма инвалидна. Ответ на то, задачи ли завершена начинается от 2 букв (Да), лучше поставить от 2

2024-09-30 10:27 UTC, pocahontassss commented on src/app/create-todos-form/create-todos-form.component.html
> +        БУЛЕАН ЗАДАЧИ ВВЕДЕНО НЕПРАВИЛНО
Корректнее будет сменить словосочетание "булеан задачи" на  "значение"

2024-09-30 12:26 UTC, rabiulawal1422 commented on src/app/users-list/user__interface.ts
исправил

2024-09-30 15:08 UTC, pocahontassss requested changes

2024-09-30 15:08 UTC, pocahontassss commented on src/app/todos-list.component/todos-list.component.component.ts
> +    this.todosService.createTodo({
добавить типизацию

2024-09-30 15:08 UTC, pocahontassss commented on src/app/users-list/users-list.component.ts
> +      id: new Date().getTime(),
добавить типизацию

2024-10-01 01:48 UTC, rabiulawal1422 commented on src/app/todos-list.component/todos-list.component.component.scss
> +  font-family: Inter;
хорошо выполнил

2024-10-01 01:50 UTC, rabiulawal1422 commented on src/app/users-list/user__interface.ts
хорошо выполнил
<img width="1680" alt="Screenshot 2024-10-01 at 10 50 22 AM" src="https://github.com/user-attachments/assets/900ad53d-8d87-4344-9072-89ff3630eeb4">

2024-10-01 01:56 UTC, rabiulawal1422 commented on src/app/create-user-form/create-user-form.component.scss
> +  width: 150px;
<img width="1680" alt="Screenshot 2024-10-01 at 10 56 23 AM" src="https://github.com/user-attachments/assets/0e4fbc70-995e-4542-b46b-9e0ea8643c81">
сделал

2024-10-01 01:58 UTC, rabiulawal1422 commented on src/app/create-todos-form/create-todos-form.component.html
> +        БУЛЕАН ЗАДАЧИ ВВЕДЕНО НЕПРАВИЛНО
<img width="1680" alt="Screenshot 2024-10-01 at 10 57 56 AM" src="https://github.com/user-attachments/assets/7a2a63f8-c59a-472e-b3cc-e668adf8856f">
готова

2024-10-01 01:59 UTC, rabiulawal1422 commented on src/app/create-todos-form/create-todos-form.component.scss
> +  margin-top: 20px;
<img width="1680" alt="Screenshot 2024-10-01 at 10 59 18 AM" src="https://github.com/user-attachments/assets/4c91a3a7-d269-4979-970e-8205d83109a7">
готова

2024-10-01 02:00 UTC, rabiulawal1422 commented on src/app/create-todos-form/create-todos-form.component.ts
> +  });
<img width="1680" alt="Screenshot 2024-10-01 at 11 00 27 AM" src="https://github.com/user-attachments/assets/a132cd25-0bb3-4bf3-89a4-00d76e2c7274">
спасибо починил

2024-10-01 03:16 UTC, rabiulawal1422 commented
<img width="1680" alt="Screenshot 2024-10-01 at 12 15 19 PM" src="https://github.com/user-attachments/assets/718cb441-4915-4cfa-9366-65b653823526">
исправил ошибки и задал вопрос по компилятору TS

2024-10-02 13:57 UTC, pocahontassss requested changes

2024-10-02 13:57 UTC, pocahontassss commented on src/app/create-todos-form/create-todos-form.component.ts
> +}
лишние пустые строки на: 16, 19. 
18 строку можно написать на 17, для лучшей читаемости кода

2024-10-02 13:57 UTC, pocahontassss commented on src/app/create-todos-form/create-todos-form.component.ts
> +}
Название валидатора - некорректное)

2024-10-07 11:33 UTC, closed without merging