Forms
RYAZHAPOVILNUR/mentoring-base pull request #73
Opened 2024-09-30 11:01 UTC by AzatGareev

@G_Venerka_A

2024-09-30 11:12 UTC, pocahontassss approved these changes

2024-09-30 15:07 UTC, pocahontassss requested changes

2024-09-30 15:07 UTC, pocahontassss commented on src/app/users-list/users-list.component.ts
> +        this.usersService.createUsers(
Добавить типизацию

2024-10-02 13:47 UTC, pocahontassss approved these changes

2024-10-02 13:47 UTC, pocahontassss commented on src/app/create-todo-form/create-todo-form.component.ts
> +        }
Можно вынести в одну строку, используя оператор || (Или)

2024-10-02 13:47 UTC, pocahontassss commented on src/app/users-list/users-list.component.ts
> +
Пора бы вынести интерфейсы в отдельную папку interfaces.
В ней будет 2 файла:
1. user-interface, в нем уже все связанные сущности (user и createUser интерфейсы)
2. todo-interface, аналогично выше

2024-10-02 23:00 UTC, AzatGareev commented on src/app/users-list/users-list.component.ts
> +
+

2024-10-02 23:00 UTC, AzatGareev commented on src/app/create-todo-form/create-todo-form.component.ts
> +        }
+

2024-10-02 23:00 UTC, AzatGareev commented on src/app/users-list/users-list.component.ts
> +        this.usersService.createUsers(
+

2024-10-03 04:47 UTC, pocahontassss approved these changes

2024-10-03 04:47 UTC, closed without merging