Routing, tasks 1,2,3
RYAZHAPOVILNUR/mentoring-base pull request #82
Opened 2024-10-03 10:33 UTC by Holin1945

2024-10-03 18:39 UTC, pocahontassss requested changes

2024-10-03 18:39 UTC, pocahontassss commented on src/assets/Line 13.svg
Нужно поработать над названиями файлов изображений. Вот статья:
https://docs.google.com/document/u/0/d/1ipRxAtW0KEC5bj-vWLNk-p8AwjsN0AWmN8YApyP9VJw/mobilebasic
(Здесь про наименование файлов изображений и как правильно указывать пути к ним)

2024-10-03 18:39 UTC, pocahontassss commented on src/app/users-list/users-list.component.html
> +<div class="component-cards-item" *ngFor="let item of users">
item можно заменить на user. Получается массив users, в котором каждый элемент - user) Логично звучит. А так получается абстрактное название item от массива пользователей - ну уже такое

2024-10-03 18:39 UTC, pocahontassss commented on src/app/users-list/users-list.component.html
> +    <button class="delete-user" (click) = "deleteUser(item.id)">УДАЛИТЬ ЮЗЕРА</button>
Здесь между = можно пробелы убрать, они лишние

2024-10-03 18:39 UTC, pocahontassss commented on src/app/header/header.component.ts
> +  isShowCatalog = !!false;
`Ты пишешь, что картинка отрисуется, если поле isManOnPhoto = false. Почему наоборот не сделать? Тогда не придется в поле isManOnPhoto писать !!false (false поменял на true, потом снова на false). Получается все перекрутил`

Помнишь этот коммент с прошлого пулл реквеста. Здесь аналогично)

2024-10-03 18:39 UTC, pocahontassss commented on src/app/header/header.component.scss
> +}
Это нужно вынести в глобальные стили

2024-10-03 18:39 UTC, pocahontassss commented on src/app/header/header.component.scss
> +}
Цвета всегда пишем в хэше. Зачем? Нам может казаться, что цвет белый, хотя он на самом деле бледно-нежно-перламутрово бежевый) Ну ты понял))) Тогда не получишь по шапке от дизайнера. Если нужна прозрачность - пишем в rgb формате

2024-10-03 18:39 UTC, pocahontassss commented on src/app/header/header.component.scss
> +  font-family: inter;
У тебя и  так применялся шрифт из-за body, в котором есть font-family Inter, здесь он уже лишний. Та и + он с большой буквы пишется, так что возможно и без body он бы  не сработал

2024-10-03 18:39 UTC, pocahontassss commented on src/app/header/header.component.scss
> +  padding: 10px 20px 10px 20px;
Можно сократить до `padding: 10px 20px`
первое значение - верх-низ
второе значение -лево-право

2024-10-03 18:39 UTC, pocahontassss commented on src/app/app.component.scss
> +}
Тоже вынести в глобальные стили, тогда данное свойство будет работать во всех компонентах, в любой точке проекта и не придется переписывать это в каждом компоненте

2024-10-04 00:45 UTC, Holin1945 commented on src/app/header/header.component.ts
> +  isShowCatalog = !!false;
Странно, я думал всё исправил

2024-10-04 08:31 UTC, Holin1945 commented on src/assets/Line 13.svg
Я его удалял уже, почему он снова появился я не знаю )))

2024-10-04 09:52 UTC, Holin1945 commented on src/app/header/header.component.scss
> +  padding: 10px 20px 10px 20px;
да, тут я затупил ))

2024-10-04 11:41 UTC, pocahontassss requested changes

2024-10-04 11:41 UTC, pocahontassss commented on src/app/normalize.scss
> +  }
Ты немного не понял. Это нужно просто вынести в глобальные стили (style scss). Тогда тебе не придется писать никакие миксины, где-то их использовать и тд. Один раз прописал и забыл про шрифт и тд. А еще у тебя на 49 и 51 строках дублируются свойства.

2024-10-04 11:41 UTC, pocahontassss commented on src/app/header/header.component.scss
> +  @include body;
Соответственно это нужно будет убрать

2024-10-04 11:41 UTC, pocahontassss commented on src/app/footer/footer.component.scss
> +  font-family: inter;
И это нужно убрать) У тебя ведь шрифт будет из-за body работать

2024-10-06 14:20 UTC, pocahontassss approved these changes

2024-10-06 14:21 UTC, closed without merging