Link Ng Material🔧
RYAZHAPOVILNUR/mentoring-base pull request #92
Opened 2024-10-07 11:22 UTC by rabiulawal1422

<img width="1680" alt="Screenshot 2024-10-07 at 8 21 02 PM" src="https://github.com/user-attachments/assets/f0853517-47cc-41f8-9254-725468ffc89b">

2024-10-07 11:40 UTC, pocahontassss requested changes

2024-10-07 11:40 UTC, pocahontassss commented on src/app/create-user-form/create-user-form.component.html
> +      "
Эти ngIf можно убрать, так как они уже встроены под капотом angular material. А так же небольшая орфографическая ошибка. Неправилно > Неправильно

2024-10-07 11:40 UTC, pocahontassss commented on src/app/create-todos-form/create-todos-form.component.html
> +    <button mat-button [disabled]="formTodo.invalid">+ Добавить Задачу</button>
`+ я делал через <mat-icon>` :)

2024-10-07 11:40 UTC, pocahontassss commented on src/app/create-todos-form/create-todos-form.component.html
> +    </mat-form-field>
аналогично с юзерами. Убрать ngIf и орфографию поправить

2024-10-08 19:29 UTC, pocahontassss approved these changes

2024-10-08 19:30 UTC, closed without merging

2024-10-11 12:55 UTC, rabiulawal1422 commented on src/app/create-todos-form/create-todos-form.component.html
> +    </mat-form-field>
выполнено

2024-10-11 12:56 UTC, shepherd1422 commented on src/app/create-todos-form/create-todos-form.component.html
> +    <button mat-button [disabled]="formTodo.invalid">+ Добавить Задачу</button>
выполнено

2024-10-11 12:56 UTC, rabiulawal1422 commented on src/app/create-user-form/create-user-form.component.html
> +      "
спасибо выполнил